CHANGELOG.md
prefect_azure/__init__.py
prefect_azure/container_instance.py
tests/test_aci_infrastructure.py

We removed prefect_azure.container_instance from `entrypoints`, but the class was is exported from the `prefect_azure` module, it does not end up in Prefect's registry. 
This PR adds `AzureContainerInstanceJob` to `__init__.py` so the infrastructure block is available directly from `prefect_azure`.
- Try to create a deployment with an `AzureContainerInstanceJob` block as the deployment's infrastructure. 
- Observe that it fails with the message `KeyError: "No class found for dispatch key 'azure-container-instance-job' in registry for type 'Block'."`
- Apply the change to `__init__.py` and observe that the deployment now succeeds.

Make `AzureContainerInstanceJob` accessible from `prefect_azure`

---

CHANGELOG.md
prefect_azure/container_instance.py
tests/test_aci_infrastructure.py

When creating a container group that uses a private container registry, the Azure SDK expects a `List[ImageRegistryCredential]` even if you only use a single registry. However, the ACI block currently tries to pass a lone `ImageRegistryCredential` instead of a list, causing an error like this:
```
azure.core.exceptions.HttpResponseError: (InaccessibleImage) The image 'myiamge.azurecr.io/my_flow:2' in container group 'container-group-id' is not accessible. Please check the image and registry credential.
```
This PR fixes the problem by passing a `List[ImageRegistryCredential]` to the Azure SDK instead of a single `ImageRegistryCredential`.
I have tested this change on Azure to verify that it works. It has also been tested and verified by a user currently running it in production.
* Create …

Fix `AzureContainerInstanceJob` private Docker registry usage

---

CHANGELOG.md
prefect_azure/container_instance.py
tests/test_aci_infrastructure.py

The Azure Container Instances Python SDK uses an `EnvironmentVariable` class for passing values that will be set as environment variables when a container starts. `EnvironmentVariable`'s constructor offers two options for setting environment variable values:
* `value`: The environment variable will be shown verbatim in logs and in the Azure Portal.
* `secure_value`: The environment variable will be obscured in logs and in the Azure Portal.
This PR:
* Adds an `ENV_SECRETS` constant containing a list of environment variables that should be treated as secure when creating ACI containers. For now, the list has a single entry: "PREFECT_API_KEY".
* Updates `AzureContainerInstanceJob` to use `secure_value` when creating an `EnvironmentVariable` instance for any environment variable in the …

Use secure ACI environment variable for PREFECT_API_KEY

---

CHANGELOG.md
prefect_azure/container_instance.py
requirements.txt
tests/test_aci_infrastructure.py

This PR adds a `kill` method to `AzureContainerInstanceJob` to support flow run cancellation added in Prefect 2.7.0. See the PR in the `prefect` repository for further detail: https://github.com/PrefectHQ/prefect/pull/7666
Small updates to exception handling, log messages and type annotations were added to other parts of `AzureContainerInstanceJob` to make it more resilient, particularly when making Azure log fetch API calls that fail sporadically when running an underpowered container under heavy load.
The only visible effect of these updates is that the user can click the big red Cancel button on the Prefect >= 2.7.0 Flow Run page:
After confirming they are sure they want to cancel the flow run, the user can check the Azure Portal to confirm that was once a happily running flow:
has now …

Add `AzureContainerInstanceJob.kill` for flow run cancellation

---

prefect_azure/credentials.py
tests/conftest.py
tests/test_credentials.py

Use default azure credential for blob storage credentials.
Closes https://github.com/PrefectHQ/prefect-azure/issues/70

Make connection string optional for blob

---

.pre-commit-config.yaml
CHANGELOG.md
prefect_azure/container_instance.py
prefect_azure/credentials.py
tests/conftest.py
tests/test_aci_infrastructure.py

Make AzureContainerInstanceCredentials optional by using default_factory. Also make tenant_id, client_id, client_secret default to None so default_factory can initialize.
Closes https://github.com/PrefectHQ/prefect-azure/issues/68

Add default azure credential

---

CHANGELOG.md
prefect_azure/blob_storage.py
tests/conftest.py
tests/test_blob_storage.py

Currently unable to pass useful kwargs to the underlying` ContainerClient.list_blobs` method to perform actions such as filtering the blob name and returning additional metadata. 
This PR extends the functionality of the `blob_storage_list` function to pass these kwargs to the underlying method to achieve this capability
```python
...
@flow
async def blob_storage_list_flow():
return await blob_storage_list(
container="prefect",
blob_storage_credentials=blob_storage_credentials,
name_starts_with="subfolder/anotherSubfolder"
include=["metadata"],
)
```
- [ x] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-azure/issues/new/choose) …

Extended blob_storage_list kwargs to mimic underlying ContainerClient.list_blobs signature

---

CHANGELOG.md
prefect_azure/workers/container_instance.py
tests/test_aci_worker.py

Current implementation requires the user to define an image either in the work pool configuration or in a deployment's `infra_overrides`. This PR enhances the `AzureContainerWorker`'s `prepare_For_flow_run` method to populate the image in the ARM template prior to executing a flow run. This will ensure that if a user did not provide an image name, the default image name will be populated in the ARM template.
This PR also updates the API version used by the default ARM template, and adds some reasonable defaults to the `AzureContainerJobConfiguration` and `AzureContainerVariables` classes.
Closes #91 
- Run `pre-commit install && pre-commit …

Add handling to set ARM template image with default when not provided by user

---

CHANGELOG.md

The library should declare itself as using types to static type checkers, as per PEP 561. That simply means adding this empty marker, as the code already makes use of types.
See https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages, and https://github.com/PrefectHQ/prefect/blob/main/src/prefect/py.typed for the corresponding file in the main prefect repo.

Add py.typed marker for PEP 561 compatibility 

---

CHANGELOG.md
docs/deployments/steps.md
docs/projects/steps.md
mkdocs.yml
prefect_azure/credentials.py
prefect_azure/deployments/steps.py
prefect_azure/projects/steps.py
prefect_azure/workers/container_instance.py
setup.py
tests/deployments/test_steps.py
tests/projects/test_steps.py

- Adds `push_to_azure_blob_storage` and `pull_from_azure_blob_storage` project steps to allow Azure Blob Storage to be used for deployment storage and retrieval. New steps follow the pattern established for existing `push` and `pull` steps.
- Cleans up docstrings and field description for `AzureBlobStorageCredentials`
- Adds logo and documentation URLs to `AzureContainerWorker`
Closes #82 
Closes #83
```yaml
prefect_version: ...
name: ...
push:
- prefect_azure.deployments.steps.push_to_azure_blob_storage:
requires: prefect-azure
container: my-container
folder: my-project
credentials: "{{ prefect.blocks.azure-blob-storage-credentials.dev-credentials }}"
pull:
- prefect_azure.deployments.steps.pull_from_azure_blob_storage:
requires: prefect-azure
container: "{{ container }}"
folder: "{{ …
```

Add `push` and `pull` steps for Azure Blob Storage

---

CHANGELOG.md
prefect_azure/credentials.py
requirements.txt
tests/test_aci_infrastructure.py

Attempts to fix an error where ACI workers aren't starting up correctly because the worker is attempting to use an `aio` version of the credentials classes with a sync version of the Container Instance client.
Closes #101 

Use aio version of credentials only with blob storage

---

CHANGELOG.md
prefect_azure/workers/container_instance.py

A fix to base job template validation in https://github.com/PrefectHQ/prefect/pull/10385 causes the default base job template for the ACI worker to fail validation. This would prevent any ACI work pools from being created. A hot fix for the `prefect-collection-registry` is in https://github.com/PrefectHQ/prefect-collection-registry/pull/278. This is the long term fix.
Closes

Adds missing variables to pass base job template validation

---

.github/workflows/tests.yml
prefect_azure/container_instance.py
prefect_azure/credentials.py
prefect_azure/workers/container_instance.py
tests/test_aci_infrastructure.py
tests/test_aci_worker.py

Following the compatibility work we've done in `prefect`, we also want to apply the
same compatibility changes to all Prefect-maintained collections.  We're following the
convention that Prefect will always use `pydantic<2` idioms, leaning on the
`pydantic.v1` module of `pydantic>2` to aid us in this.  With these changes, we can
operate normally regardless of the installed version.
Until `prefect` fully deprecates `pydantic` versions below 2.0, we'll continue to
maintain that constraint of using only v1 idioms.
This is part of a series of identical PRs for all of our maintained collections.

Conditional imports to support operating with `pydantic>2` installed

---

prefect_azure/credentials.py

Subscription ID format can at times be confusing, especially for those who've dealt with Azure Resource Manager. 
There is a `subscription.id` and a `subscriptionId`.
From Azure docs:
https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-scope#subscription
`subscription()` returns:
```
{
"id": "/subscriptions/{subscription-id}",
"subscriptionId": "{subscription-id}",
...
}
```

Explicitly state Subscription ID format

---

CHANGELOG.md
prefect_azure/container_instance.py
prefect_azure/workers/container_instance.py
requirements.txt
tests/test_aci_infrastructure.py
tests/test_aci_worker.py

Updates imports of the deprecated Docker modules to the new versions (introduced in https://github.com/PrefectHQ/prefect/pull/8788 & [Prefect 2.10.11](https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#release-21011)):
- Change `prefect.infrastructure.docker` to `prefect.infrastructure.container`
- Change `prefect.docker` to `prefect.utilities.dockerutils`
- Bump minimum Prefect version to 2.10.11

Update deprecated docker module imports

---

CHANGELOG.md
prefect_azure/deployments/steps.py

Switches to the sync version of `DefaultAzureCredential` to resolve errors when using default credentials with the deployment steps in this library.
Closes https://github.com/PrefectHQ/prefect/issues/10764
Closes #115

Fix error in deployment steps

---

.github/workflows/tests.yml
requirements.txt

As part of our work adding support for Pydantic 2, we removed its pin in 
`prefect`'s `requirements.txt`. This means that it's possible to have 
`prefect`, `pydantic>=2`, and any version of this collection installed. But, 
the collection(s) only support `pydantic>=2` in their latest versions. This 
PR adds a pin on the collection's `requirements.txt` to make sure that it is 
only installed with the correct version `prefect` that supports `pydantic>=2`

Update the pin on `prefect` version

---

CHANGELOG.md
prefect_azure/container_instance.py
requirements.txt
tests/test_aci_infrastructure.py
tests/test_aci_worker.py

Implements generate_work_pool_base_job_template on the `AzureContainerInstanceJob` block to allow users to use an `AzureContainerInstanceJob`infrastructure block to create a `azure-container-instance` work pool.

Adds ability to publish `AzureContainerInstanceJob block` as a `azure-container-instance` work pool

---

CHANGELOG.md
prefect_azure/workers/container_instance.py

Closes https://github.com/PrefectHQ/prefect-azure/issues/112

Fix worker arm template name length

---

prefect_azure/deployments/steps.py

Add note on Hierarchical Namespace for Azure Storage Account. I ran into a hard to understand issue since the code was being downloaded from a Blob Container with Hierarchical Namespace which meant that `.list_blobs()` had both the folder name and file name as seperate files it tried to download. An idea for another addition could be a check to see if the Storage Account has Hierarchical Namespace enabled before listing Blobs.
Closes #126
Closes https://github.com/PrefectHQ/prefect/issues/11211

Add note on Hierarchical Namespace for Azure Storage Account

---

prefect_azure/blob_storage.py
tests/conftest.py
tests/test_blob_storage.py
tests/test_ml_datastore.py

Adds an `AzureBlobStorageContainer` block as a replacement for the `Azure` block in the core library. Works for both deployment flow code storage and result storage.
Closes https://github.com/PrefectHQ/prefect-azure/issues/135
```python
from prefect_azure import AzureBlobStorageCredentials
from prefect_azure.blob_storage import AzureBlobStorageContainer
credentials = AzureBlobStorageCredentials(
connection_string="connection_string",
)
container = AzureBlobStorageContainer(
container_name="container",
credentials=credentials,
)
container.download_folder_to_path(
from_folder="folder",
to_folder="local_folder"
)
```
- Run `pre-commit install …

Add `AzureBlobStorageContainer` block

---

prefect_azure/__init__.py

Adds an import for `AzureBlobStorageContainer` at the top level of the package to ensure it is registered in the Prefect object registry. This will allow users to load this block type with `Block.load(azure-blob-storage-container/{block_document_name})`.
Closes #144 

Expose `AzureBlobStorageContainer` block at top level to ensure it is registered with Prefect's ojbect registry

---

prefect_azure/workers/container_instance.py

closes https://github.com/PrefectHQ/prefect-azure/issues/146
we previously attempted to get the `len` of a `UUID` without first casting to a `str`

Fix logic to keep ACI deployment name within Azure character limit error
